project:
  type: website
  output-dir: docs

website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy vs GDP
      - href: life-population.qmd
        text: Life Expectancy vs Population
      - href: country.qmd
        text: Changes in India

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true



